[pytest]
pythonpath = . src
addopts = --cov=app --cov-report=term-missing --cov-report=xml
filterwarnings =
    ignore:.*Using `httpx` with `starlette.testclient` is deprecated.*:starlette.exceptions.StarletteDeprecationWarning
    ignore:.*Module .* was previously imported, but not measured.*:coverage.exceptions.CoverageWarning
